### ISSUE TITLE
Could not create or apply app

### ISSUE THREAD

**Issue by tangjiaxing669** [mesos/docker-compose-executor#19]
I exist marathon and mesos cluster.

```
marathon version 1.3.6
mesos version 1.1.0
```

this is my marathon json file format:

```
{
  "id": "docker-compose-demo",
  "cmd": null,
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "constraints": [["hostname", "CLUSTER", "slave3"]],
  "executor": "/usr/local/src/compose_executor.sh",
  "labels": {
      "fileName": "/root/docker-compose.yml"
  },
  "container": {}
}
```

```
[root@slave3 src]# cat /usr/local/src/compose_executor.sh 
#!/bin/bash
COMPOSE_JAR_NAME=/usr/local/src/docker-compose-executor_0.1.1.jar
java -jar ${COMPOSE_JAR_NAME}
[root@slave3 src]# cd
[root@slave3 ~]# cat docker-compose.yml 
version: '2'
services:
  mysql:
    image: vmware/harbor-db:0.5.0
    container_name: harbor-db
    restart: always
    volumes:
      - /data/database:/var/lib/mysql
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
[root@slave3 ~]# 
```

When I click the `Create Application` button, the tips are as follows:

```
There was a problem with your configuration
general: Unknown server error. Could not create or apply app.
```

When I change my marathon json file format:

```
{
  "id": "docker-compose-demo",
  "cmd": null,
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "constraints": [["hostname", "CLUSTER", "slave3"]],
  "executor": "/usr/local/src/compose_executor.sh",
  "labels": {
      "fileName": "/root/docker-compose.yml"
  }
}
```

When I click the `Create Application` button, the tips are as follows:

```
There was a problem with your configuration
general: AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'.
```

Please help!
